"""add draft_generation_logs

Revision ID: 2cb97efd1a30
Revises: 7309849873a8
Create Date: 2026-07-06 16:16:54.029063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb97efd1a30'
down_revision: Union[str, Sequence[str], None] = '7309849873a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_generation_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('post_draft_id', sa.Text(), nullable=False),
    sa.Column('today_input_type', sa.Text(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('all_options_passed', sa.Boolean(), nullable=False),
    sa.Column('failed_option_count', sa.Integer(), nullable=False),
    sa.Column('research_performed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['post_draft_id'], ['post_drafts.id'], name='draft_generation_logs_post_draft_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('draft_generation_logs_post_draft_id_idx', 'draft_generation_logs', ['post_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('draft_generation_logs_post_draft_id_idx', table_name='draft_generation_logs')
    op.drop_table('draft_generation_logs')
    # ### end Alembic commands ###
