"""reconcile prisma-era schema drift

Revision ID: b930df179645
Revises: 0ba5abb056df
Create Date: 2026-07-06 19:07:53.868435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b930df179645'
down_revision: Union[str, Sequence[str], None] = '0ba5abb056df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('oauth_accounts_provider_provider_id_key'), table_name='oauth_accounts')
    op.create_unique_constraint('oauth_accounts_provider_provider_id_key', 'oauth_accounts', ['provider', 'provider_id'])
    op.create_index('oauth_accounts_user_id_idx', 'oauth_accounts', ['user_id'], unique=False)
    op.drop_constraint(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key('oauth_accounts_user_id_fkey', 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_draft_options_post_draft_id_fkey'), 'post_draft_options', type_='foreignkey')
    op.create_foreign_key('post_draft_options_post_draft_id_fkey', 'post_draft_options', 'post_drafts', ['post_draft_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_drafts_selected_option_id_fkey'), 'post_drafts', type_='foreignkey')
    op.drop_constraint(op.f('post_drafts_product_id_fkey'), 'post_drafts', type_='foreignkey')
    op.create_foreign_key('post_drafts_selected_option_id_fkey', 'post_drafts', 'post_draft_options', ['selected_option_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('post_drafts_product_id_fkey', 'post_drafts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_analyses', 'differentiators',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.drop_index(op.f('product_analyses_product_id_key'), table_name='product_analyses')
    op.create_unique_constraint('product_analyses_product_id_key', 'product_analyses', ['product_id'])
    op.drop_constraint(op.f('product_analyses_product_id_fkey'), 'product_analyses', type_='foreignkey')
    op.create_foreign_key('product_analyses_product_id_fkey', 'product_analyses', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('threads_connections_user_id_fkey'), 'threads_connections', type_='foreignkey')
    op.create_foreign_key('threads_connections_user_id_fkey', 'threads_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('voice_profiles_user_id_fkey'), 'voice_profiles', type_='foreignkey')
    op.create_foreign_key('voice_profiles_user_id_fkey', 'voice_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('voice_profiles_user_id_fkey', 'voice_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('voice_profiles_user_id_fkey'), 'voice_profiles', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('threads_connections_user_id_fkey', 'threads_connections', type_='foreignkey')
    op.create_foreign_key(op.f('threads_connections_user_id_fkey'), 'threads_connections', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('product_analyses_product_id_fkey', 'product_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('product_analyses_product_id_fkey'), 'product_analyses', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('product_analyses_product_id_key', 'product_analyses', type_='unique')
    op.create_index(op.f('product_analyses_product_id_key'), 'product_analyses', ['product_id'], unique=True)
    op.alter_column('product_analyses', 'differentiators',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_constraint('post_drafts_product_id_fkey', 'post_drafts', type_='foreignkey')
    op.drop_constraint('post_drafts_selected_option_id_fkey', 'post_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('post_drafts_product_id_fkey'), 'post_drafts', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('post_drafts_selected_option_id_fkey'), 'post_drafts', 'post_draft_options', ['selected_option_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('post_draft_options_post_draft_id_fkey', 'post_draft_options', type_='foreignkey')
    op.create_foreign_key(op.f('post_draft_options_post_draft_id_fkey'), 'post_draft_options', 'post_drafts', ['post_draft_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('oauth_accounts_user_id_fkey', 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('oauth_accounts_user_id_idx', table_name='oauth_accounts')
    op.drop_constraint('oauth_accounts_provider_provider_id_key', 'oauth_accounts', type_='unique')
    op.create_index(op.f('oauth_accounts_provider_provider_id_key'), 'oauth_accounts', ['provider', 'provider_id'], unique=True)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    # ### end Alembic commands ###
