services:
  postgres:
    image: postgres:17-alpine
    container_name: varogo_postgres
    environment:
      POSTGRES_USER: varogo
      POSTGRES_PASSWORD: varogo_password
      POSTGRES_DB: varogo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: varogo_cloudflared
    command: tunnel run varogo-dev
    volumes:
      - /Users/wang/.cloudflared:/etc/cloudflared:ro
    restart: unless-stopped

volumes:
  postgres_data:
