services:
  postgres:
    image: postgres:17-alpine
    container_name: varogo_postgres
    environment:
      POSTGRES_USER: varogo
      POSTGRES_PASSWORD: varogo_password
      POSTGRES_DB: varogo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
